# Generated by Django 5.1.6 on 2026-01-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=50, unique=True)),
                ('school_name', models.CharField(max_length=255)),
            ],
        ),
    ]
