# Generated by Django 5.1.6 on 2026-01-30 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('degree_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('degree_name', models.CharField(max_length=255)),
                ('degree_code', models.CharField(max_length=50, unique=True)),
                ('degree_duration', models.PositiveIntegerField(help_text='Duration in years')),
                ('number_of_semesters', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255)),
                ('school_code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dept_code', models.CharField(max_length=20)),
                ('dept_name', models.CharField(max_length=100)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='Creation.degree')),
            ],
            options={
                'unique_together': {('degree', 'dept_code'), ('degree', 'dept_name')},
            },
        ),
        migrations.AddField(
            model_name='degree',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='Creation.school'),
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('regulation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regulation_code', models.CharField(help_text='e.g. R20', max_length=50)),
                ('batch', models.CharField(help_text='e.g. 2020-2024', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulations', to='Creation.degree')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('degree', 'regulation_code', 'batch')},
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('sem_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sem_number', models.PositiveIntegerField()),
                ('sem_name', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='Creation.degree')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semesters', to='Creation.department')),
            ],
            options={
                'ordering': ['sem_number'],
                'unique_together': {('degree', 'sem_number')},
            },
        ),
    ]
