# Generated by Django 6.0.1 on 2026-01-22 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='id',
        ),
        migrations.AddField(
            model_name='school',
            name='school_code',
            field=models.CharField(default='TEMP_CODE', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='school_short_name',
            field=models.CharField(default='TEMP_CODE', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('degree_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('degree_name', models.CharField(max_length=255)),
                ('degree_code', models.CharField(max_length=50, unique=True)),
                ('degree_duration', models.PositiveIntegerField(help_text='Duration in years')),
                ('number_of_semesters', models.PositiveIntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='Creation.school')),
            ],
        ),
    ]
