# Generated by Django 5.1.6 on 2026-02-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
