# Generated by Django 6.0.1 on 2026-01-22 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creation', '0002_remove_school_id_school_school_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dept_code', models.CharField(max_length=20)),
                ('dept_name', models.CharField(max_length=100)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='Creation.degree')),
            ],
            options={
                'unique_together': {('degree', 'dept_code'), ('degree', 'dept_name')},
            },
        ),
    ]
