# Generated by Django 5.1.6 on 2026-01-24 06:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creation', '0003_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('sem_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sem_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sem_name', models.CharField(max_length=50)),
                ('sem_short_name', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('annual_exam', models.BooleanField(default=False)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='Creation.degree')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='Creation.department')),
            ],
            options={
                'unique_together': {('degree', 'department', 'sem_name'), ('degree', 'department', 'sem_number')},
            },
        ),
    ]
