# Generated by Django 5.1.6 on 2026-01-24 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creation', '0004_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('regulation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regulation_code', models.CharField(help_text='e.g. MR25', max_length=50, unique=True)),
                ('batch', models.CharField(help_text='e.g. 2025-2026', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulations', to='Creation.degree')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
