# Generated by Django 5.1.6 on 2026-01-30 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creation', '0005_regulation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['sem_number']},
        ),
        migrations.AlterUniqueTogether(
            name='regulation',
            unique_together={('degree', 'regulation_code', 'batch')},
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_short_name',
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('degree', 'sem_number')},
        ),
        migrations.AlterField(
            model_name='regulation',
            name='batch',
            field=models.CharField(help_text='e.g. 2020-2024', max_length=20),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='regulation_code',
            field=models.CharField(help_text='e.g. R20', max_length=50),
        ),
        migrations.AlterField(
            model_name='semester',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semesters', to='Creation.department'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='sem_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveField(
            model_name='regulation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='annual_exam',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='sem_short_name',
        ),
    ]
