# Generated by Django 5.1.6 on 2026-02-13 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Creation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(help_text='Unique Employee ID', max_length=50, unique=True)),
                ('faculty_name', models.CharField(max_length=255)),
                ('faculty_email', models.EmailField(max_length=254, unique=True)),
                ('faculty_mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('faculty_date_of_birth', models.DateField(blank=True, null=True)),
                ('faculty_gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentAdminAssignment',
            fields=[
                ('assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this department admin assignment', primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this assignment was created')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active')),
                ('assigned_by', models.ForeignKey(help_text='Campus admin who created this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_admin_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('degree', models.ForeignKey(help_text='Degree to which this department belongs (must be under selected school)', on_delete=django.db.models.deletion.CASCADE, to='Creation.degree')),
                ('department', models.ForeignKey(help_text='Department being managed by this admin (must be under selected degree)', on_delete=django.db.models.deletion.CASCADE, to='Creation.department')),
                ('school', models.ForeignKey(help_text='School to which this department belongs', on_delete=django.db.models.deletion.CASCADE, to='Creation.school')),
                ('faculty', models.ForeignKey(help_text='Faculty member assigned as department admin', on_delete=django.db.models.deletion.CASCADE, related_name='dept_admin_assignments', to='UserDataManagement.faculty')),
            ],
            options={
                'verbose_name': 'Department Admin Assignment',
                'verbose_name_plural': 'Department Admin Assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('faculty', 'department')},
            },
        ),
        migrations.CreateModel(
            name='FacultyMapping',
            fields=[
                ('mapping_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Creation.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='UserDataManagement.faculty')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.school')),
            ],
            options={
                'unique_together': {('faculty', 'school', 'department')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roll_no', models.CharField(max_length=30)),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_gender', models.CharField(max_length=10)),
                ('student_date_of_birth', models.DateField()),
                ('student_phone_number', models.CharField(max_length=15)),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_phone_number', models.CharField(max_length=15)),
                ('batch', models.CharField(max_length=20)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='Creation.degree')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='Creation.department')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='Creation.regulation')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='Creation.semester')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['roll_no'],
                'unique_together': {('department', 'roll_no')},
            },
        ),
    ]
