# Generated by Django 5.1.6 on 2026-01-30 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentAdminAssignment',
            fields=[
                ('assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this department admin assignment', primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this assignment was created')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active')),
            ],
            options={
                'verbose_name': 'Department Admin Assignment',
                'verbose_name_plural': 'Department Admin Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(help_text='Unique Employee ID', max_length=50, unique=True)),
                ('faculty_name', models.CharField(max_length=255)),
                ('faculty_email', models.EmailField(max_length=254, unique=True)),
                ('faculty_mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('faculty_date_of_birth', models.DateField(blank=True, null=True)),
                ('faculty_gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyMapping',
            fields=[
                ('mapping_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roll_no', models.CharField(max_length=30)),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_gender', models.CharField(max_length=10)),
                ('student_date_of_birth', models.DateField()),
                ('student_phone_number', models.CharField(max_length=15)),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_phone_number', models.CharField(max_length=15)),
                ('batch', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['roll_no'],
            },
        ),
    ]
