# Generated by Django 5.1.6 on 2026-01-30 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Creation', '0001_initial'),
        ('UserDataManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentadminassignment',
            name='assigned_by',
            field=models.ForeignKey(help_text='Campus admin who created this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_admin_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departmentadminassignment',
            name='degree',
            field=models.ForeignKey(help_text='Degree to which this department belongs (must be under selected school)', on_delete=django.db.models.deletion.CASCADE, to='Creation.degree'),
        ),
        migrations.AddField(
            model_name='departmentadminassignment',
            name='department',
            field=models.ForeignKey(help_text='Department being managed by this admin (must be under selected degree)', on_delete=django.db.models.deletion.CASCADE, to='Creation.department'),
        ),
        migrations.AddField(
            model_name='departmentadminassignment',
            name='school',
            field=models.ForeignKey(help_text='School to which this department belongs', on_delete=django.db.models.deletion.CASCADE, to='Creation.school'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departmentadminassignment',
            name='faculty',
            field=models.ForeignKey(help_text='Faculty member assigned as department admin', on_delete=django.db.models.deletion.CASCADE, related_name='dept_admin_assignments', to='UserDataManagement.faculty'),
        ),
        migrations.AddField(
            model_name='facultymapping',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Creation.department'),
        ),
        migrations.AddField(
            model_name='facultymapping',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='UserDataManagement.faculty'),
        ),
        migrations.AddField(
            model_name='facultymapping',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='Creation.degree'),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='Creation.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='regulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='Creation.regulation'),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='Creation.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentadminassignment',
            unique_together={('faculty', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='facultymapping',
            unique_together={('faculty', 'school', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('department', 'roll_no')},
        ),
    ]
