# Generated by Django 5.1.6 on 2026-01-28 05:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creation', '0005_regulation'),
        ('UserDataManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='department',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='school',
        ),
        migrations.CreateModel(
            name='FacultyMapping',
            fields=[
                ('mapping_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Creation.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='UserDataManagement.faculty')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.school')),
            ],
            options={
                'unique_together': {('faculty', 'school', 'department')},
            },
        ),
    ]
