# Generated by Django 5.1.6 on 2026-01-29 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creation', '0005_regulation'),
        ('UserDataManagement', '0002_remove_faculty_department_remove_faculty_school_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentAdminAssignment',
            fields=[
                ('assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this department admin assignment', primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this assignment was created')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active')),
                ('assigned_by', models.ForeignKey(help_text='Campus admin who created this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_admin_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('degree', models.ForeignKey(help_text='Degree to which this department belongs (must be under selected school)', on_delete=django.db.models.deletion.CASCADE, to='Creation.degree')),
                ('department', models.ForeignKey(help_text='Department being managed by this admin (must be under selected degree)', on_delete=django.db.models.deletion.CASCADE, to='Creation.department')),
                ('faculty', models.ForeignKey(help_text='Faculty member assigned as department admin', on_delete=django.db.models.deletion.CASCADE, related_name='dept_admin_assignments', to='UserDataManagement.faculty')),
                ('school', models.ForeignKey(help_text='School to which this department belongs', on_delete=django.db.models.deletion.CASCADE, to='Creation.school')),
            ],
            options={
                'verbose_name': 'Department Admin Assignment',
                'verbose_name_plural': 'Department Admin Assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('faculty', 'department')},
            },
        ),
    ]
