# Generated by Django 5.1.6 on 2026-01-30 09:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creation', '0006_alter_semester_options_and_more'),
        ('UserDataManagement', '0003_departmentadminassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={},
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='dob',
            new_name='faculty_date_of_birth',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='email',
            new_name='faculty_email',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='gender',
            new_name='faculty_gender',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='mobile_no',
            new_name='faculty_mobile_no',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='full_name',
            new_name='faculty_name',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='faculty_id',
            new_name='id',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roll_no', models.CharField(max_length=30)),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_gender', models.CharField(max_length=10)),
                ('student_date_of_birth', models.DateField()),
                ('student_phone_number', models.CharField(max_length=15)),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_phone_number', models.CharField(max_length=15)),
                ('batch', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='Creation.degree')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='Creation.department')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='Creation.regulation')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='Creation.semester')),
            ],
            options={
                'ordering': ['roll_no'],
                'unique_together': {('department', 'roll_no')},
            },
        ),
    ]
