# Generated by Django 6.0.1 on 2026-01-25 13:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_name', models.CharField(help_text='Unique name of the section (e.g., A, B, Alpha)', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'sections',
                'ordering': ['section_name'],
            },
        ),
    ]
