# Generated by Django 5.1.6 on 2026-02-12 09:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(help_text='Bonafide / Memo / TC / etc', max_length=100)),
                ('message', models.TextField(blank=True, help_text='Optional message from student', null=True)),
                ('status', models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('IN_HOLD', 'In Hold (Need Details)'), ('APPROVED', 'Approved'), ('ISSUED', 'Issued'), ('REJECTED', 'Rejected')], default='UNDER_REVIEW', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRequestHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
