# Generated by Django 5.1.6 on 2026-02-19 04:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CourseConfiguration', '0003_course_course_short_name'),
        ('Creation', '0001_initial'),
        ('UserDataManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REGISTERED', 'Registered')], default='DRAFT', max_length=15)),
                ('total_credits', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_locked', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='UserDataManagement.student')),
            ],
            options={
                'unique_together': {('student', 'semester', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(help_text='Bona fide / Memo / Certificate / TC etc', max_length=100)),
                ('purpose', models.TextField(help_text='Reason for requesting the document')),
                ('supporting_doc', models.FileField(blank=True, null=True, upload_to='student_service_requests/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('ON_HOLD', 'On Hold'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('READY', 'Ready/Issued')], default='SUBMITTED', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='UserDataManagement.student')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRequestHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='StudentServices.documentrequest')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistrationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseConfiguration.course')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='StudentServices.courseregistration')),
            ],
            options={
                'unique_together': {('registration', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseRegistrationWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(help_text='e.g. 2025-26', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reg_windows_regulation', to='Creation.regulation')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reg_windows_semester', to='Creation.semester')),
            ],
            options={
                'verbose_name': 'Course Registration Window',
                'unique_together': {('regulation', 'semester', 'academic_year')},
            },
        ),
    ]
