# Generated by Django 5.1.6 on 2026-02-23 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StudentServices', '0001_initial'),
        ('UserDataManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='UserDataManagement.student'),
        ),
        migrations.AddField(
            model_name='documentrequesthistory',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='StudentServices.documentrequest'),
        ),
    ]
