# Generated by Django 5.1.6 on 2026-02-23 04:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AcademicSetup', '0001_initial'),
        ('Creation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAllocation',
            fields=[
                ('allocation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('timetable_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('academic_year', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualSection',
            fields=[
                ('virtual_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. CSE-A-Java or Elective-Cyber-G1', max_length=100)),
                ('academic_year', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Virtual Section',
                'verbose_name_plural': 'Virtual Sections',
            },
        ),
        migrations.CreateModel(
            name='AcademicClass',
            fields=[
                ('class_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('strength', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.degree')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.department')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.regulation')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademicSetup.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.semester')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicClassStudent',
            fields=[
                ('mapping_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='CourseManagement.academicclass')),
            ],
        ),
    ]
