# Generated by Django 5.1.6 on 2026-02-13 12:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AcademicSetup', '0001_initial'),
        ('CourseConfiguration', '0001_initial'),
        ('Creation', '0001_initial'),
        ('UserDataManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicClass',
            fields=[
                ('class_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('strength', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.degree')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.department')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.regulation')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademicSetup.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.semester')),
            ],
            options={
                'unique_together': {('department', 'semester', 'section', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='FacultyAllocation',
            fields=[
                ('allocation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_allocations', to='CourseManagement.academicclass')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_allocations', to='CourseConfiguration.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_allocations', to='UserDataManagement.faculty')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.semester')),
            ],
            options={
                'unique_together': {('faculty', 'course', 'academic_class', 'semester', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='AcademicClassStudent',
            fields=[
                ('mapping_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='CourseManagement.academicclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserDataManagement.student')),
            ],
            options={
                'unique_together': {('academic_class', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('timetable_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('academic_year', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='CourseManagement.academicclass')),
                ('faculty_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='CourseManagement.facultyallocation')),
            ],
            options={
                'unique_together': {('academic_class', 'day_of_week', 'start_time', 'academic_year')},
            },
        ),
    ]
