# Generated by Django 5.1.6 on 2026-02-23 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CourseConfiguration', '0002_initial'),
        ('CourseManagement', '0001_initial'),
        ('Creation', '0001_initial'),
        ('UserDataManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicclassstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserDataManagement.student'),
        ),
        migrations.AddField(
            model_name='facultyallocation',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_allocations', to='CourseManagement.academicclass'),
        ),
        migrations.AddField(
            model_name='facultyallocation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_allocations', to='CourseConfiguration.course'),
        ),
        migrations.AddField(
            model_name='facultyallocation',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_allocations', to='UserDataManagement.faculty'),
        ),
        migrations.AddField(
            model_name='facultyallocation',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.semester'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='CourseManagement.academicclass'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='faculty_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='CourseManagement.facultyallocation'),
        ),
        migrations.AddField(
            model_name='virtualsection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_sections', to='CourseConfiguration.course'),
        ),
        migrations.AddField(
            model_name='virtualsection',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.degree'),
        ),
        migrations.AddField(
            model_name='virtualsection',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.department'),
        ),
        migrations.AddField(
            model_name='virtualsection',
            name='regulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.regulation'),
        ),
        migrations.AddField(
            model_name='virtualsection',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.school'),
        ),
        migrations.AddField(
            model_name='virtualsection',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.semester'),
        ),
        migrations.AddField(
            model_name='virtualsection',
            name='students',
            field=models.ManyToManyField(related_name='virtual_sections', to='UserDataManagement.student'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='virtual_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtual_timetables', to='CourseManagement.virtualsection'),
        ),
        migrations.AddField(
            model_name='facultyallocation',
            name='virtual_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtual_allocations', to='CourseManagement.virtualsection'),
        ),
        migrations.AlterUniqueTogether(
            name='academicclass',
            unique_together={('department', 'semester', 'section', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='academicclassstudent',
            unique_together={('academic_class', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('academic_class', 'virtual_section', 'day_of_week', 'start_time', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='facultyallocation',
            unique_together={('faculty', 'course', 'academic_class', 'virtual_section', 'semester', 'academic_year')},
        ),
    ]
