# Generated by Django 5.1.6 on 2026-02-20 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseConfiguration', '0005_remove_studentselection_is_locked'),
        ('CourseManagement', '0001_initial'),
        ('Creation', '0001_initial'),
        ('UserDataManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualSection',
            fields=[
                ('virtual_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. CSE-A-Java or Elective-Cyber-G1', max_length=100)),
                ('academic_year', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_sections', to='CourseConfiguration.course')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.degree')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.department')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.regulation')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.school')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creation.semester')),
                ('students', models.ManyToManyField(related_name='virtual_sections', to='UserDataManagement.student')),
            ],
            options={
                'verbose_name': 'Virtual Section',
                'verbose_name_plural': 'Virtual Sections',
            },
        ),
        migrations.AlterUniqueTogether(
            name='facultyallocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='facultyallocation',
            name='virtual_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtual_allocations', to='CourseManagement.virtualsection'),
        ),
        migrations.AlterUniqueTogether(
            name='facultyallocation',
            unique_together={('faculty', 'course', 'academic_class', 'virtual_section', 'semester', 'academic_year')},
        ),
    ]
