# Generated by Django 5.1.6 on 2026-02-20 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseManagement', '0002_virtualsection_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='virtual_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtual_timetables', to='CourseManagement.virtualsection'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='CourseManagement.academicclass'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('academic_class', 'virtual_section', 'day_of_week', 'start_time', 'academic_year')},
        ),
    ]
