# Generated by Django 5.1.6 on 2026-02-02 08:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Creation', '0002_regulation_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=50, unique=True)),
                ('course_type', models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective'), ('OPEN_ELECTIVE', 'Open Elective'), ('LAB', 'Lab')], max_length=20)),
                ('batch', models.CharField(max_length=50)),
                ('credit_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lecture_hours', models.PositiveIntegerField(default=0)),
                ('tutorial_hours', models.PositiveIntegerField(default=0)),
                ('practical_hours', models.PositiveIntegerField(default=0)),
                ('course_category', models.CharField(choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Practical'), ('PROJECT', 'Project')], max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Creation.degree')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Creation.department')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Creation.regulation')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Creation.school')),
            ],
            options={
                'unique_together': {('course_code', 'regulation', 'batch')},
            },
        ),
    ]
