# Generated by Django 5.1.6 on 2026-02-13 12:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Creation', '0001_initial'),
        ('UserDataManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=50, unique=True)),
                ('course_type', models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective'), ('OPEN_ELECTIVE', 'Open Elective'), ('LAB', 'Lab')], max_length=20)),
                ('batch', models.CharField(max_length=50)),
                ('credit_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lecture_hours', models.PositiveIntegerField(default=0)),
                ('tutorial_hours', models.PositiveIntegerField(default=0)),
                ('practical_hours', models.PositiveIntegerField(default=0)),
                ('course_category', models.CharField(choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Practical'), ('PROJECT', 'Project')], max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Creation.degree')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Creation.department')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Creation.regulation')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Creation.school')),
            ],
            options={
                'unique_together': {('course_code', 'regulation', 'batch')},
            },
        ),
        migrations.CreateModel(
            name='RegistrationWindow',
            fields=[
                ('window_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch', models.CharField(max_length=50)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_windows', to='Creation.department')),
                ('elective_subjects', models.ManyToManyField(related_name='elective_in_windows', to='CourseConfiguration.course')),
                ('major_subjects', models.ManyToManyField(related_name='major_in_windows', to='CourseConfiguration.course')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_windows', to='Creation.regulation')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_windows', to='Creation.school')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_windows', to='Creation.semester')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='StudentSelection',
            fields=[
                ('selection_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(related_name='selected_by_students', to='CourseConfiguration.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_selections', to='UserDataManagement.student')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='CourseConfiguration.registrationwindow')),
            ],
            options={
                'unique_together': {('student', 'window')},
            },
        ),
    ]
