# Generated by Django 5.1.6 on 2026-02-17 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseConfiguration', '0001_initial'),
        ('Creation', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_code', 'regulation')},
        ),
        migrations.RemoveField(
            model_name='course',
            name='batch',
        ),
    ]
