# Generated by Django 5.1.6 on 2026-02-02 15:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseConfiguration', '0001_initial'),
        ('Creation', '0003_degree_created_at_degree_is_active_degree_updated_at_and_more'),
        ('UserDataManagement', '0003_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationWindow',
            fields=[
                ('window_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_windows', to='Creation.department')),
                ('elective_subjects', models.ManyToManyField(related_name='elective_in_windows', to='CourseConfiguration.course')),
                ('major_subjects', models.ManyToManyField(related_name='major_in_windows', to='CourseConfiguration.course')),
                ('regulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_windows', to='Creation.regulation')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_windows', to='Creation.school')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_windows', to='Creation.semester')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='StudentSelection',
            fields=[
                ('selection_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(related_name='selected_by_students', to='CourseConfiguration.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_selections', to='UserDataManagement.student')),
                ('window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='CourseConfiguration.registrationwindow')),
            ],
            options={
                'unique_together': {('student', 'window')},
            },
        ),
    ]
