# Generated by Django 5.1.6 on 2026-02-12 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CourseConfiguration', '0001_initial'),
        ('UserDataManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentselection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_selections', to='UserDataManagement.student'),
        ),
        migrations.AddField(
            model_name='studentselection',
            name='window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='CourseConfiguration.registrationwindow'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_code', 'regulation', 'batch')},
        ),
        migrations.AlterUniqueTogether(
            name='studentselection',
            unique_together={('student', 'window')},
        ),
    ]
