# Generated by Django 5.1.6 on 2026-02-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseConfiguration', '0002_alter_course_unique_together_remove_course_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_short_name',
            field=models.CharField(blank=True, help_text='Abbreviated course name', max_length=50, null=True),
        ),
    ]
