# Generated by Django 5.1.6 on 2026-02-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseConfiguration', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentselection',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
