# Generated by Django 5.1.6 on 2026-02-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseConfiguration', '0003_course_course_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentselection',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
