# Generated by Django 5.1.6 on 2026-02-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseConfiguration', '0004_studentselection_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentselection',
            name='is_locked',
        ),
    ]
