# Generated by Django 5.1.6 on 2026-02-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfasession',
            name='action',
            field=models.CharField(blank=True, default='', help_text='Specific action this MFA is for', max_length=255, null=True),
        ),
    ]
