# Generated by Django 6.0.1 on 2026-01-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfasession',
            name='duo_status',
            field=models.CharField(default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='mfasession',
            name='duo_txid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='duo_username',
            field=models.CharField(blank=True, help_text='Duo username or user_id for Duo API calls', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mfasession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mfasession',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
