# Generated by Django 6.0.1 on 2026-01-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CAMPUS_ADMIN', 'Campus Admin'), ('DEPARTMENT_ADMIN', 'DEPT ADMIN'), ('FACULTY', 'Faculty'), ('STUDENT', 'Student')], default='STUDENT', max_length=30),
        ),
    ]
