# Generated by Django 6.0.1 on 2026-01-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0008_alter_user_id_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COLLEGE_ADMIN', 'college admin'), ('ACADEMIC_COORDINATOR', 'accedemic coordinator'), ('FACULTY', 'Faculty'), ('STUDENT', 'Student')], default='STUDENT', max_length=30),
        ),
    ]
