"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import jwt

# Monkeypatch jwt.decode to add leeway for clock skew issues (fixes ImmatureSignatureError in allauth)
original_decode = jwt.decode
def patched_decode(*args, **kwargs):
    # Ensure leeway is at least 15 seconds to avoid ImmatureSignatureError
    current_leeway = kwargs.get('leeway', 0)
    # SimpleJWT might pass a timedelta, while others pass int seconds
    if hasattr(current_leeway, 'total_seconds'):
        current_leeway = current_leeway.total_seconds()
    
    kwargs['leeway'] = max(int(float(current_leeway or 0)), 15)
    return original_decode(*args, **kwargs)
jwt.decode = patched_decode

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f%6w)!8+*k_u+t%u68fgxnhvvzrxbhyrt)9fr2mbtuz^sq(p27'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'custom_auth',
    'Creation',
    'AcademicSetup',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True # For development
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
         'BACKEND': 'django.template.backends.django.DjangoTemplates',  
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Email / SMTP configuration (use environment variables in production)
import os
from pathlib import Path
from dotenv import load_dotenv

# Load .env from project root for local development (ignored in production if you prefer other secret stores)
BASE_DIR = Path(__file__).resolve().parent.parent
dotenv_path = BASE_DIR / '.env'
if dotenv_path.exists():
    load_dotenv(dotenv_path, override=True)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'anonymousvoice4business@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'xavn mapa wzlq nsqc')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Duo MFA configuration (set these in environment variables in production)
# DUO_INTEGRATION_KEY and DUO_SECRET_KEY are provided by Duo; DUO_API_HOST is the Duo API hostname
# IMPORTANT: these should reference ENV VAR NAMES (not secret values). Do NOT hardcode secrets in the repo.
DUO_INTEGRATION_KEY = os.environ.get('DUO_INTEGRATION_KEY')
DUO_SECRET_KEY = os.environ.get('DUO_SECRET_KEY')
DUO_API_HOST = os.environ.get('DUO_API_HOST')  # e.g. 'api-xxxxxxxx.duosecurity.com'
# Optional: timeout for Duo API calls (seconds)
DUO_API_TIMEOUT = int(os.environ.get('DUO_API_TIMEOUT', '10'))

# Optional: secret used to verify incoming Duo webhook requests (HMAC-SHA256)
# Configure this in Duo's Webhook settings and set DUO_WEBHOOK_SECRET to the same value
DUO_WEBHOOK_SECRET = os.environ.get('DUO_WEBHOOK_SECRET')

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'custom_auth.User'


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'ROTATE_REFRESH_TOKENS': True,
    'LEEWAY': timedelta(seconds=15), # Added leeway for our own tokens too
}

# NOTE: Role checks use hardcoded values in application code per project requirement.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
} 

# =====================================================
# GOOGLE SIGN-IN / ALLAUTH CONFIGURATION
# =====================================================

SITE_ID = 1

INSTALLED_APPS += [
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth',
    'dj_rest_auth.registration',
]

MIDDLEWARE += [
    'allauth.account.middleware.AccountMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# allauth / socialaccount settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_AUTO_SIGNUP = False
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID'),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET'),
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

REST_USE_JWT = True
REST_AUTH_TOKEN_MODEL = None
REST_SESSION_LOGIN = False # dj-rest-auth: don't use the default token model since we use JWT
 


