# Generated by Django 5.1.6 on 2026-01-30 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Creation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('calendar_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('batch', models.CharField(max_length=50)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='academic_calendars/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='Creation.degree')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='Creation.department')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='Creation.regulation')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='Creation.school')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='Creation.semester')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INSTRUCTION', 'Instruction Period'), ('HOLIDAY', 'Holiday'), ('EXAM', 'Examination'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='AcademicSetup.academiccalendar')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Section Name (e.g. A, B, Section 1)', max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=60, help_text='Max student capacity')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Creation.degree')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Creation.department')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Creation.regulation')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Creation.school')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Creation.semester')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeTableTemplate',
            fields=[
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_templates', to='Creation.degree')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_templates', to='Creation.department')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_templates', to='Creation.school')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_templates', to='Creation.semester')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('slot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_order', models.PositiveIntegerField()),
                ('slot_type', models.CharField(blank=True, help_text='e.g. Theory, Lab, Break', max_length=50, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='AcademicSetup.timetabletemplate')),
            ],
            options={
                'ordering': ['day', 'slot_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='academiccalendar',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('regulation', 'batch', 'semester'), name='unique_active_calendar'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('regulation', 'batch', 'department', 'semester', 'name'), name='unique_section_per_context'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('template', 'day', 'slot_order'), name='unique_template_day_slot_order'),
        ),
    ]
