# Generated by Django 5.1.6 on 2026-01-25 05:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicSetup', '0001_initial'),
        ('Creation', '0005_regulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTableTemplate',
            fields=[
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_templates', to='Creation.degree')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_templates', to='Creation.department')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_templates', to='Creation.school')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_templates', to='Creation.semester')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('slot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_order', models.PositiveIntegerField()),
                ('slot_type', models.CharField(blank=True, help_text='e.g. Theory, Lab, Break', max_length=50, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='AcademicSetup.timetabletemplate')),
            ],
            options={
                'ordering': ['day', 'slot_order'],
                'constraints': [models.UniqueConstraint(fields=('template', 'day', 'slot_order'), name='unique_template_day_slot_order')],
            },
        ),
    ]
