# Generated by Django 5.2.10 on 2026-01-25 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Creation', '0005_regulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendar_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('holiday_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('scope', models.CharField(choices=[('CAMPUS', 'Campus Wide'), ('DEGREE', 'Degree Specific'), ('DEPARTMENT', 'Department Specific')], max_length=20)),
                ('reason', models.CharField(max_length=255)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='calendar_holidays.calendar')),
                ('degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Creation.degree')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Creation.department')),
            ],
            options={
                'unique_together': {('calendar', 'date', 'scope', 'degree', 'department')},
            },
        ),
    ]
