# Generated by Django 5.2.10 on 2026-01-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_holidays', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together={('name', 'academic_year')},
        ),
    ]
